#!/bin/bash

######### START CONFIGURATION #########
. moo_config

######### START FUNCTIONS #########
. moo_functions

echo "Current version: 0.$MOO_VERSION"

echo "Next Version: 0.$(( $(echo $MOO_VERSION) + 1 ))"
exit 0

pkgver=$(LC_ALL=C date -u +%Y%m%d)
cd /tmp
rm blacklist.txt
wget https://projects.parabolagnulinux.org/blacklist.git/plain/blacklist.txt -O blacklist.txt

cut -d: -f1,2 blacklist.txt | \
      sed "s/:$//" | \
      grep -v ":" | \
      #grep -E -o '.{0,99}:' | \
      #sed "s/://g" | \
      grep -v '^#' | \

      ## example cheat line
      sed "s/steam/zteam/g" | \
      sed "s/nvidia/zvidia/g" | \
      ## end

      #sed "s/:/ /g" | \
      sort -u > list_a

less list_a

exit 0