#!/bin/bash
# manage Storage

# must be run as root
if [[ $EUID != 0 ]]; then
  	printf "%s\n" "You must be root to run this."
  	exit 1
fi

# unecrypt and mount container
if [[ "$1" == "open" ]]; then
	cryptsetup open --type luks /dev/sdc1 Storage
	mount -t ext4 /dev/mapper/Storage /media/Storage
# close
elif [[ "$1" == "close" ]]; then
	umount /media/Storage
	cryptsetup close Storage
# test
elif [[ "$1" == "test" ]]; then
	if [[ -f "/media/Storage/test" ]]; then
		exit 0
	else
	    exit 1
	fi
else
  	printf "%s\n" "Options are open or close or test."
fi

if [[ -f "/media/Storage/test" ]]; then
    exit 0
else
    exit 1
fi
