#!/bin/bash
# manage backup2

# must be run as root
if [[ $EUID != 0 ]]; then
  	printf "%s\n" "You must be root to run this."
  	exit 1
fi

# unecrypt and mount container
if [[ "$1" == "open" ]]; then
	cryptsetup open --type luks /dev/sdb1 backup2
	mount -t ext4 /dev/mapper/backup2 /media/backup2
# close
elif [[ "$1" == "close" ]]; then
	umount /media/backup2
	cryptsetup close backup2
else
  	printf "%s\n" "Options are open or close."
fi

if [[ -f "/media/backup2/test" ]]; then
    exit 0
else
    exit 1
fi
