#!/bin/bash
# manage backup3

# must be run as root
if [[ $EUID != 0 ]]; then
  	printf "%s\n" "You must be root to run this."
  	exit 1
fi

# unecrypt and mount container
if [[ "$1" == "open" ]]; then
	cryptsetup open --type luks /dev/sdb backup3
	mount -t ext4 /dev/mapper/backup3 /media/backup3
# close
elif [[ "$1" == "close" ]]; then
	umount /media/backup3
	cryptsetup close backup3
# test
elif [[ "$1" == "test" ]]; then
	if [[ -f "/media/backup3/test" ]]; then
		exit 0
	else
	    exit 1
	fi
else
  	printf "%s\n" "Options are open or close or test."
fi

if [[ -f "/media/backup3/test" ]]; then
    exit 0
else
    exit 1
fi
