#!/bin/bash

#strace -eopen unity > unitystrace.log
#LD_DEBUG=files unity > unity.log 2>&1
#valgrind -v --leak-check=full unity 2>&1 > unityvalgrind.log

Xephyr -ac -br -noreset -screen 1024x768 :2.0 &
sleep 1
DISPLAY=:2.0 gnome-session

exit 0
