#!/bin/bash

URL="https://duckdfuckgo.com/"

while :
do
	resp=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "$URL")
	if [ $resp != "200" ]; then
		echo "$resp - $(date)" >> ~/checksite.log
	fi
	sleep 5s
done
