#!/bin/bash
[ -z "$(pidof urxvtd)" ] && [ -f /usr/bin/urxvtd ] && urxvtd -q -o -f

# welcome audio message
#ogg123 -q "${HOME}/.config/awesome/sounds/voice-welcome.ogg"
#cowsay -f "$(ls /usr/share/cows/ | sort -R | head -1)" "$(fortune -s)"
#ogg123 -q "${HOME}/.config/awesome/sounds/voice-please-confirm.ogg"

# ssh-agent
[ -z "$(pidof keychain)" ] && eval $(keychain --eval --agents ssh -Q --quiet id_rsa)

[ -z "$(pidof gpg-agent)" ] && eval $(gpg-agent --daemon) &

exit 0
