#!/usr/bin/sh
## pdq@archlinux
## 08-04-2013

## can be used in firefox with addon Open With 5.3.1 https://addons.mozilla.org/en-US/firefox/addon/open-with/
## Copy embedded video link - ~/bin/grake_url copy
## Play embedded video link in VLC - ~/bin/grake_url


if [ ! -f /usr/bin/grake ]; then
	echo "Missing package: grake [Command line tool for scanning webpages for Youtube links]"
	exit 1
elif [ ! -f /usr/bin/xclip ]; then
	echo "Missing package: xclip [Command line interface to the X11 clipboard]"
	exit 1
elif [ ! -f /usr/bin/vlc ]; then
	echo "Missing package: vlc [A multi-platform MPEG, VCD/DVD, and DivX player]"
	exit 1
fi

if [ "$1" != "" ]; then
	if [ "$1" = "copy" ]; then
		grake -q --proxy="http://127.0.0.1:8118" "$2" | xclip
		notify-send "Link copied to clipboard"
	else
		PROXY=$(zenity --list --radiolist --width 200 --height 200 --text "Flash sucks" --title="Play video in VLC" --column "Choice" --column "Use Proxy" TRUE Yes FALSE No)
		RES=$(zenity --list --radiolist --width 200 --height 230 --text "Flash sucks" --title="Play video in VLC" --column "Choice" --column "Resolution" TRUE 240p  FALSE 480p FALSE 720p FALSE 1080p)
		_USEPROX=$([ "$_PROXY" == "Yes" ] && echo "--http-proxy=127.0.0.1:8118 " || echo "")
		grake -q --proxy="http://127.0.0.1:8118" "$1" | vlc $_USEPROX--preferred-resolution="$RES" -
	fi
fi

exit 0
