#!/bin/sh
# Install mooOS

do_sudo=
## root script
if [ $(id -u) -ne 0 ]; then
   do_sudo="sudo "
fi

# Main Program 
# Welcome the user, allow for early exit if not interested
dialog --title "mooOS Installer" --yesno "Welcome to mooOS Installer..  \nContinue?" 10 30

# If the user decided to continue, moo
if [[ $? -ne 1 ]]; then
	cd /home/$USER/Github/
	rm -r mooOS-dev-tools/
	git clone git://github.com/idk/mooOS-dev-tools.git
	chmod +x /home/$USER/Github/mooOS-dev-tools/installer/installer.sh
 	$do_sudo/home/$USER/Github/mooOS-dev-tools/installer/installer.sh
fi
