#!/bin/sh
## tested onArch Linux x86_64
## 03-20-2013 pdq

## ensure dialog is installed
if [ -f /usr/bin/dialog ] && [ -f /usr/bin/ogg123 ]; then

    ## start urxvt daemon
    [ -z "$(pidof urxvtd)" ] && urxvtd -q -o -f

    ## start clipboard manager
    killall -q autocutsel
    autocutsel -fork &
    autocutsel -selection PRIMARY -fork &

    ## export some variables
    export BROWSER=firefox
    export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

    ## login sound
    ogg123 -q "${HOME}/.config/awesome/sounds/voice-system-activated.ogg"

    ## truecrypt mounted success file
    if [ -f "/media/truecrypt1/test" ] ; then
        ogg123 -q "${HOME}/.config/awesome/sounds/desktop-login.ogg"
    fi

    ## dialog menubox
    wm_cmd=(dialog --keep-tite --menu "Select interface:" 22 76 16)
    wm_options=(1 'e17' 
                2 'Awesome Window Manager'
                3 'kde'
                4 'Razor-QT'
                11 'Configure'
                666 'Reboot')

    choices=$("${wm_cmd[@]}" "${wm_options[@]}" 2>&1 >/dev/tty)

    ## execute selected option
    for choice in $choices
    do
        case $choice in
            1)
                exec enlightenment_start
                ;;
            2)
                exec awesome >> "$HOME"/.cache/awesome/stdout 2>> "$HOME"/.cache/awesome/stderr
                ;;
            3)
                exec startkde
                ;;
            4)
                exec razor-session
                ;;
            11)
                nano "$HOME"/.xinitrc
                ;;
            666) 
                reboot
                ;;
        esac
    done 
else
    echo "Install the packages dialog and ogg123 ... then re-run"
fi

exit 0