#!/usr/bin/bash
# notify user when network is up

while true
do
	wget -q --timeout=5 https://archlinux.org -O "/dev/null"
	if [[ $? -eq 0 ]]; then
        notify-send "TOR is up" -i "network"
        break
	else
        notify-send "TOR is initializing" -i "error"
        sleep 10s
	fi
done

exit 0
