#!/usr/bin/bash
# notify user when network is up

while true
do
	wget -q --timeout=10 https://sourceforge.net -O "/dev/null"
	if [[ $? -eq 0 ]]; then
        notify-send "Network (TOR) is up" -i "network"
        break
	else
        notify-send "Network (TOR) is initializing" -i "error"
        sleep 9s
	fi
done

exit 0
