#!/bin/bash
echo ":: updating system..."
echo "pacaur -Syua"
#packer-color -Syu --auronly
pacaur -Syua
#yaourt -Syua
echo " "
echo ":: update complete..."
echo " "
sleep 2s
echo ":: this window will automatically close after 15 minutes"
echo ":: ctrl+c to manually exit"
notify-send "AUR" \
            "Update complete" \
            -i /home/pdq/.config/awesome/icons/pacman_icon_48x48.png
sleep 15m
exit