#!/bin/bash
# pacman update
echo ":: updating system..."
echo "sudo pacman-color -Syu"
sudo pacman-color -Syu
echo " "
echo ":: update complete..."
echo " "
sleep 2s
echo ":: this window will automatically close after 15 minutes"
echo ":: ctrl+c to manually exit"
notify-send "Pacman" \
            "Update complete" \
            -i /home/pdq/.config/awesome/icons/pacman_icon_48x48.png
            
   
sleep 15m
exit