#!/usr/bin/bash
# pacman update
echo ":: updating system..."
echo "sudo pacman -Syyu"
sudo pacman -Syu
echo " "
echo ":: update complete..."
echo "Updated main packages. [Enter] to update AUR packages."
notify-send "Main" \
            "Update complete" \
            -i /usr/share/moo-tools/mooOS.png
read foobar
echo ":: updating system [AUR]..."
echo "pacaur -Syua"
#packer -Syu --auronly
pacaur -Syua
#yaourt -Syua
echo " "
echo ":: update complete..."
echo "Updated AUR packages. [Enter] to close."
notify-send "[AUR]" \
            "Update complete" \
            -i /usr/share/moo-tools/mooOS.png
read foobar

exit 0
