#!/bin/bash

# welcome audio message
mplayer "${HOME}/.config/awesome/sounds/voice-welcome.ogg"

mplayer "${HOME}/.config/awesome/sounds/voice-please-confirm.ogg"

mplayer "${HOME}/.config/awesome/sounds/voice-piy.ogg"

mplayer "${HOME}/.config/awesome/sounds/voice-accepted.ogg"

#mplayer "${HOME}/.config/awesome/sounds/voice-access-denied.ogg"


exit 0
