#!/bin/bash

 clear

 echo
 echo
 echo -n "Enter a domain: "
 read domain

 if [ -z $domain ]; then
         echo
         echo "You did not enter a domain"
         exit
 fi
 echo
 echo "Starting recon on $domain"

 read -p "Press <enter> to continue. "


$BROWSER -new-tab https://www.intodns.com/$domain &
sleep 1
