#!/usr/bin/sh
REPO_BASE_DIR="/mnt/linux-pdq/media/truecrypt1/domains/mooOS/"
REPO_BASE_URL="https://repo.mooos.pdq/"
ABS_BASE_DIR="$HOME/abs/"
REPO_LOG_TEMP="/tmp/repo_renew"
REPO_LOG="${ABS_BASE_DIR}update.log"

## remove existing repos
rm ${ABS_BASE_DIR}mooOS-pkgs-32/mooOS-pkgs-32.db.tar.gz
rm ${ABS_BASE_DIR}mooOS-pkgs-64/mooOS-pkgs-64.db.tar.gz
#rm ${ABS_BASE_DIR}mooOS-utils/mooOS-utils.db.tar.gz

## create repo databases
repo-add ${ABS_BASE_DIR}mooOS-pkgs-32/mooOS-pkgs-32.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-32/*.pkg.tar.xz > $REPO_LOG_TEMP
repo-add ${ABS_BASE_DIR}mooOS-pkgs-64/mooOS-pkgs-64.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-64/*.pkg.tar.xz >> $REPO_LOG_TEMP
#repo-add ${ABS_BASE_DIR}mooOS-utils/mooOS-utils.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-64/*.pkg.tar.xz >> $REPO_LOG_TEMP

## format log a little
echo $(date -d "today" +"%Y%m%d%H%M") >> $REPO_LOG
sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" $REPO_LOG_TEMP >> $REPO_LOG


## clean up stable repos
rm -r ${ABS_BASE_DIR}mooOS-pkgs-32-out-of-date ${ABS_BASE_DIR}mooOS-pkgs-64-out-of-date
mv ${REPO_BASE_DIR}mooOS-pkgs-32 ${ABS_BASE_DIR}mooOS-pkgs-32-out-of-date
mv ${REPO_BASE_DIR}mooOS-pkgs-64 ${ABS_BASE_DIR}mooOS-pkgs-64-out-of-date
#mv ${REPO_BASE_DIR}mooOS-utils ${ABS_BASE_DIR}mooOS-utils-out-of-date
cp -r ${ABS_BASE_DIR}mooOS-pkgs-32 ${REPO_BASE_DIR}mooOS-pkgs-32
cp -r ${ABS_BASE_DIR}mooOS-pkgs-64 ${REPO_BASE_DIR}mooOS-pkgs-64
#cp -r ${ABS_BASE_DIR}mooOS-utils ${REPO_BASE_DIR}mooOS-utils

notify-send "Repo update complete"

exit 0