#!/bin/bash

PWD=$(pwd)
MOO_HOME=$HOME/
## patch config files for username
cd ${MOO_HOME}config/standard
for NEW_FILE in e.*
do
	EWW_FILE=${NEW_FILE/.cfg/.src}

	eet -d $NEW_FILE config $EWW_FILE
	sed -i "s/pdq/moo/g" $EWW_FILE
	rm $NEW_FILE
	eet -e $NEW_FILE config $EWW_FILE 1
	rm $EWW_FILE
done
cd $PWD