#!/bin/sh

IFS=$'\n'

## makes sure station name is not exact match with any other ###########
## Video stream list updated 06.25.2013 ################################
STREAMLIST='
Al Jazeera English| -v -r rtmp://aljazeeraflashlivefs.fplive.net/aljazeeraflashlive-live/aljazeera_eng_med 
CNN| -r rtmp://a.cdn.msnbclive.eu/edge/cnn_live -W "http://msnbclive.eu/player.swf" -p http://blog.livenewschat.tv/situation-chatroom 
CNN International News| -v -r rtmp://a.cdn.msnbclive.eu/edge/cnni_live -W "http://msnbclive.eu/getswf.php?name=player.swf" -p http://blog.livenewschat.tv/international-room-chat 
CSPAN1| -v -r rtmp://cp82346.live.edgefcs.net:1935/live -y CSPAN1@14845 -W http://www.c-span.org/cspanVideoHD.swf -p http://www.c-span.org/Live-Video/C-SPAN/ 
CSPAN2| -v -r rtmp://cp82347.live.edgefcs.net:1935/live -y CSPAN2@14846 -W http://www.c-span.org/cspanVideoHD.swf -p http://www.c-span.org/Live-Video/C-SPAN2/ 
CSPAN3| -v -r rtmp://cp82348.live.edgefcs.net:1935/live -y CSPAN3@14847 -W http://www.c-span.org/cspanVideoHD.swf -p http://www.c-span.org/Live-Video/C-SPAN3/ 
MSNBC| -v -r "rtmp://a.cdn.msnbclive.eu/edge" -y msnbc_live -W "http://msnbclive.eu/getswf.php?name=player.swf" -p "http://www.rentadrone.tv/msnbc-live-rockinroosters/""
Russia Today News, English| -v -r rtmp://fms5.visionip.tv/live -a live -W http://rt.com/s/swf/player5.4.viral.swf -p http://rt.com/on-air/ -y RT_2 
Russia Today News, English HD| -v -r rtmp://rt.fms-04.visionip.tv/live/rt-global-live-HD -a live -W http://rt.com/s/swf/player5.4.viral.swf
'
########################################################################


## VIDEO ###############################################################

function VIDEO () {
clear

  tput smul
   echo ""
   echo ":: Streaming TV ::"
   echo ":: Select Channel ::"
   tput rmul
   echo " "
   
   ## selection entry text
   PS3="`tput bold`Enter Station Number To Play > `tput sgr0`"
   
   select STREAM in `echo "$STREAMLIST" | cut -d"|" -f1 | sort -u`  "Quit" ; do
  
    [[ "$STREAM" == "Quit" ]] && echo "Goodbye...." && exit	      ## exit script
    
    ## get stream command / urls
    GETURL=`echo "$STREAMLIST" | grep -w -m1 "^$STREAM" | cut -d"|" -f2 `
    
    if [[ -n "$GETURL" ]]; then 
    ## show selected channel name
    tput smso &&  echo " >:Attempt connection to video stream $STREAM:< "  && tput rmso 
    ## play stream - remove -q to see what rtmpdump is doing - change media player here   
    eval rtmpdump -q "$GETURL" | vlc -  &>/dev/null
    else
    ## no selection message
    tput setf 4 && echo "Not a menu entry - please select again" && tput sgr0
    fi
  
 done
}


########################################################################

case $1 in
  "-v")
  VIDEO
  ;;
  
  *) 
  echo -e "Use /path/to/streamplay \n  -v For Video \n"
  ;;
  esac
 exit 
