#!/usr/bin/sh
# original code by skizzhg

#BROWSER=dwb

case "$1" in
	-video)
		_PROXY=$(zenity --list --radiolist --width 200 --height 230 --text "Flash sucks" --title="" --column "Choice" --column "Use Proxy" TRUE Yes FALSE No)
		_RES=$(zenity --list --radiolist --width 200 --height 200 --text "Flash sucks" --title="Play video in VLC" --column "Choice" --column "Resolution" TRUE 240p  FALSE 480p FALSE 720p FALSE 1080p)
		_USEPROX=$([ "$_PROXY" == "Yes" ] && echo "--http-proxy=127.0.0.1:8118 " || echo "")
		vlc $_USEPROX--preferred-resolution "$_RES" "$2" &
		;;
	-audio)
		vlc --http-proxy=127.0.0.1:8118 "$2" &
		;;
	-image)
		img=$(torsocks wget "$2" --spider -o /dev/stdout | grep '\[image/')
		#if [[ -n "$img" ]]; then
			feh -xZF "$2"
		#else
		#	$BROWSER "$2" &>/dev/null
		#fi
		;;
	-www)
		$BROWSER "$2" &>/dev/null
		;;
	*)
		$BROWSER "$1" &>/dev/null
		;;
esac
