#!/usr/bin/sh
## pdq@archlinux
## Part of pdq-browser 0.0.1
## This script is for launching vimb
## 08-04-2013

WEBBROWSER=$HOME/abs/vimb/vimb
MANPAGE=$HOME/abs/vimb/usr/local/share/man/man1/vimb.1

if [ ! -f $WEBBROWSER ]; then
	echo "Missing package: vimb [Vimb is a WebKit-based web browser]"
	exit 1
elif [ ! -f /usr/bin/tabbed ]; then
	echo "Missing package: tabbed [Simple generic tabbed fronted to xembed aware applications]"
	exit 1
fi

while getopts u:pthm option
do
        case "${option}"
        in
                u) URL=${OPTARG};;
                p) PROXY=YES;;
                h) HELP=YES;;
                m) MANUAL=YES;;
        esac
done

if [ "$HELP" != "" ]; then
	$WEBBROWSER -h
elif [ "$MANUAL" != "" ]; then
	man $MANPAGE
elif [ "$PROXY" != "" ]; then
	http_proxy=http://127.0.0.1:8118 tabbed -c -n proxy $WEBBROWSER "$URL" -e
else
	tabbed -c -n browser $WEBBROWSER "$URL" -e
fi