#!/usr/bin/sh

VID_DIR="$HOME/Videos/tmp/"
YTUSER="$@"
YTUSER=$(echo $YTUSER | tr " " "+")
START_HERE=$(pwd)

mkdir -p "$VID_DIR$YTUSER"
cd "$VID_DIR$YTUSER"
grake "https://www.youtube.com/user/$YTUSER" | cclive
cd "$START_HERE"

exit 0